services:
  gem_development:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - firebird_test
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    working_dir: /app
    environment:
      - BUNDLE_PATH=/usr/local/bundle

  firebird_test:
    image: firebirdsql/firebird:latest
    environment:
      - FIREBIRD_DATABASE=test.fdb
      - FIREBIRD_USER=test_user
      - FIREBIRD_PASSWORD=test_password
      - ISC_PASSWORD=masterkey
    volumes:
      - firebird_data:/firebird/data

volumes:
  bundle_cache:
  firebird_data:
