services:
  gem_development:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - firebird3
      - firebird4
      - firebird5
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    working_dir: /app
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - ISC_PASSWORD=masterkey
      - FIREBIRD_DATABASE=/firebird/data/test.fdb
      - RAILS_ENV=test
      - BUNDLE_DEPLOYMENT=true
      - DB_HOST=firebird3  # Usar el nombre del servicio Docker
    networks:
      - firebird_net
    restart: unless-stopped

  firebird3:
    image: firebirdsql/firebird:3
    container_name: firebird3
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_DATABASE=/firebird/data/test.fdb
    ports:
      - "3053:3050"
    volumes:
      - firebird3_data:/firebird/data
      - ./spec/db:/firebird/data
    networks:
      - firebird_net
    restart: unless-stopped

  firebird4:
    image: firebirdsql/firebird:4
    container_name: firebird4
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_DATABASE=/firebird/data/test.fdb
    ports:
      - "3051:3050"
    volumes:
      - firebird4_data:/firebird/data
      - ./spec/db:/firebird/data
    networks:
      - firebird_net
    restart: unless-stopped

  firebird5:
    image: firebirdsql/firebird:5
    container_name: firebird5
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_DATABASE=/firebird/data/test.fdb
    ports:
      - "3052:3050"
    volumes:
      - firebird5_data:/firebird/data
      - ./spec/db:/firebird/data
    networks:
      - firebird_net
    restart: unless-stopped

volumes:
  bundle_cache:
  firebird3_data:
  firebird4_data:
  firebird5_data:

networks:
  firebird_net:
    driver: bridge